version: '2'

services:
  testMongo:
    image: "mongo:latest"
    command: mongod --storageEngine wiredTiger --auth
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb_test:/data/db
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
